version: "3.5"

services:
  sapo-server:
    image: golang:1.15.2-alpine
    container_name: sapo-server-app
    restart: always
    volumes:
      - .:/go/src/github.com/bbkbbbk/sapo
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/github.com/bbkbbbk/sapo
    ports:
      - 8080:8080
    env_file:
      - .env.local
    command: go run main.go